set(_CATKIN_CURRENT_PACKAGE "peach_bot_2dnav")
set(peach_bot_2dnav_VERSION "0.0.0")
set(peach_bot_2dnav_MAINTAINER "Nathan Burnham <nburn42@gmail.com>")
set(peach_bot_2dnav_PACKAGE_FORMAT "1")
set(peach_bot_2dnav_BUILD_DEPENDS )
set(peach_bot_2dnav_BUILD_EXPORT_DEPENDS "move_base" "tf")
set(peach_bot_2dnav_BUILDTOOL_DEPENDS "catkin")
set(peach_bot_2dnav_BUILDTOOL_EXPORT_DEPENDS )
set(peach_bot_2dnav_EXEC_DEPENDS "move_base" "tf")
set(peach_bot_2dnav_RUN_DEPENDS "move_base" "tf")
set(peach_bot_2dnav_TEST_DEPENDS )
set(peach_bot_2dnav_DOC_DEPENDS )
set(peach_bot_2dnav_DEPRECATED "")